# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Byeong Kim
email: byeong.kim0430@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full stack developer student passionate about designing efficient web applications and maximising a user experience.
  My goal is to create beautifully designed web tools with clean code to improve users' everyday life.
  Aside from writing code, I like to go for a long walk or travel around the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  byeong0430

# Build settings
markdown: kramdown
