# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Byeong Kim
role: Junior Web Developer
email: byeong.kim0430@gmail.com
telephone: 778-887-3994
description: > # this means to ignore newlines until "baseurl:"
  Junior full stack web developer with a degree in physical geography.<br/>
  When I was working as an Air Quality Specialist, I took it upon myself to upgrade my team's web app as well as the database.
  I quickly fell in love with learning new programming languages and decided to make a career change.<br/>
  I am passionate about designing efficient web applications and maximising user experience.
  My goal is to create beautiful web tools with clean code to improve users' everyday life.
  Aside from writing code, I like to go for long walks or travel around the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://byeong0430.github.io" # the base hostname & protocol for your site
github_username:  byeong0430
linked_in_shortUrl: byeong-kim-a385ba47
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
